# Generated by Django 6.1 on 2026-08-31 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'User Login'), ('REGISTER', 'User Registration'), ('CREATE', 'Resource Created'), ('UPDATE', 'Resource Updated'), ('DELETE', 'Resource Deleted'), ('CHECKOUT', 'Order Checkout'), ('PAYMENT', 'Payment Attempt'), ('REFUND', 'Refund Requested'), ('ADMIN_ACTION', 'Admin Override')], default='UPDATE', max_length=50)),
                ('method', models.CharField(default='POST', max_length=10)),
                ('path', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('status_code', models.IntegerField(default=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
